"""darkmode added gto the admin model

Revision ID: 274c71725e03
Revises: 49887bffaf99
Create Date: 2025-03-16 20:28:21.994653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274c71725e03'
down_revision = '49887bffaf99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    # ### end Alembic commands ###
