"""finalists added to the contestant model

Revision ID: 310e5f782fe1
Revises: fa45b78f6b40
Create Date: 2025-03-15 16:02:32.962633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310e5f782fe1'
down_revision = 'fa45b78f6b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contestants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalist', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contestants', schema=None) as batch_op:
        batch_op.drop_column('finalist')

    # ### end Alembic commands ###
